# Generated by Django 4.2.5 on 2023-09-06 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20230906_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='e_mail',
            new_name='email',
        ),
    ]
